/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package factura.vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import factura.dao.ConexionBD;

/**
 *
 * @author USUARIO
 */
public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
        actualizarClientes(); // Llamada al método para actualizar el combo box al iniciar
        actualizarProductos(); // Llamada al método para actualizar el combo box de productos al iniciar
        cbxClienteFactura.addActionListener(evt -> cbxClienteFacturaActionPerformed(evt));
        
        // Centrar la ventana en la pantalla
        setLocationRelativeTo(null);
    }

    private void actualizarClientes() {
        try (Connection conexion = ConexionBD.obtenerConexion()) {
            String sql = "SELECT nombre FROM clientes";
            try (PreparedStatement ps = conexion.prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) {
                cbxClienteFactura.removeAllItems();
                while (rs.next()) {
                    cbxClienteFactura.addItem(rs.getString("nombre"));
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al actualizar clientes: " + e.getMessage());
        }
    }

    private void actualizarProductos() {
        System.out.println("Actualizando productos..."); // Mensaje de depuración
        try (Connection conexion = ConexionBD.obtenerConexion()) {
            String sql = "SELECT nombre FROM productos";
            try (PreparedStatement ps = conexion.prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) {
                cbxProducto.removeAllItems();
                while (rs.next()) {
                    cbxProducto.addItem(rs.getString("nombre"));
                }
            }
        } catch (SQLException e) {
            System.err.println("Error en la base de datos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNroFactura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        cbxClienteFactura = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaFactura = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cbxProducto = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FACTURA");

        jLabel2.setText("No :");

        jLabel3.setText("Fecha :");

        jLabel4.setText("Cliente :");

        jLabel5.setText("Observaciones :");

        jLabel6.setText("Total :");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        cbxClienteFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxClienteFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClienteFacturaActionPerformed(evt);
            }
        });

        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane3.setViewportView(tablaFactura);

        jLabel7.setText("Producto :");

        cbxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(evt -> btnRegistrarActionPerformed(evt));

        btnAgregar.setText("+");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        // Corrección del diseño para incluir el JLabel "FACTURA" en el grupo horizontal
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Aseguramos que el JLabel esté incluido
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAgregar)))
                            .addComponent(txtNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxClienteFactura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFecha))
                                .addGap(34, 34, 34)
                                .addComponent(btnRegistrar)))
                        .addGap(5, 5, 5)))
                .addGap(63, 63, 63))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1) // Aseguramos que el JLabel esté incluido
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxClienteFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClienteFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClienteFacturaActionPerformed
        if (cbxClienteFactura.getSelectedItem() != null) {
            System.out.println("Cliente seleccionado: " + cbxClienteFactura.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbxClienteFacturaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try (Connection conexion = ConexionBD.obtenerConexion()) {
            // Consultar los datos del producto desde la base de datos
            String sql = "SELECT codigo, nombre, precio FROM productos WHERE nombre = ?";
            try (PreparedStatement ps = conexion.prepareStatement(sql)) {
                ps.setString(1, cbxProducto.getSelectedItem().toString());
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        // Obtener los datos del producto
                        String codigo = rs.getString("codigo");
                        String nombre = rs.getString("nombre");
                        double precio = rs.getDouble("precio");

                        // Calcular el subtotal (cantidad por precio)
                        int cantidad = 1; // Por defecto, agregar 1 unidad
                        double subtotal = precio * cantidad;

                        // Agregar una nueva fila al inicio de la tabla
                        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaFactura.getModel();
                        model.insertRow(0, new Object[]{codigo, nombre, precio, cantidad, subtotal});

                        // Actualizar el total
                        double totalActual = txtTotal.getText().isEmpty() ? 0 : Double.parseDouble(txtTotal.getText());
                        totalActual += subtotal;
                        txtTotal.setText(String.valueOf(totalActual));
                    }
                }
            } catch (SQLException e) {
                System.err.println("Error en la base de datos: " + e.getMessage());
            }
        } catch (SQLException e) {
            System.err.println("Error al agregar el producto: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try (Connection conexion = ConexionBD.obtenerConexion()) {
            // Obtener el idCliente basado en el nombre seleccionado en el combo box
            String clienteSeleccionado = cbxClienteFactura.getSelectedItem().toString();
            int idCliente = -1;
            String sqlCliente = "SELECT idCliente FROM clientes WHERE nombre = ?";
            try (PreparedStatement psCliente = conexion.prepareStatement(sqlCliente)) {
                psCliente.setString(1, clienteSeleccionado);
                try (ResultSet rsCliente = psCliente.executeQuery()) {
                    if (rsCliente.next()) {
                        idCliente = rsCliente.getInt("idCliente");
                    }
                }
            }

            if (idCliente == -1) {
                throw new SQLException("No se encontró el cliente seleccionado en la base de datos.");
            }

            // Insertar la factura en la base de datos
            String sqlFactura = "INSERT INTO facturas (idFactura, numeroFactura, fecha, idCliente, observaciones, total) VALUES (?, ?, ?, ?, ?, ?)";
            try (PreparedStatement psFactura = conexion.prepareStatement(sqlFactura)) {
                psFactura.setInt(1, obtenerNuevoIdFactura()); // Método para obtener el nuevo ID
                psFactura.setString(2, txtNroFactura.getText());
                psFactura.setString(3, txtFecha.getText());
                psFactura.setInt(4, idCliente); // Usar el idCliente obtenido
                psFactura.setString(5, txtObservaciones.getText());
                psFactura.setDouble(6, Double.parseDouble(txtTotal.getText()));
                psFactura.executeUpdate();
            }

            // Limpiar el formulario y la tabla
            txtNroFactura.setText("");
            txtFecha.setText("");
            cbxClienteFactura.setSelectedIndex(0);
            txtObservaciones.setText("");
            txtTotal.setText("");
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaFactura.getModel();
            model.setRowCount(0);

            System.out.println("Factura registrada correctamente.");
        } catch (SQLException e) {
            System.err.println("Error en la base de datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Factura().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxClienteFactura;
    private javax.swing.JComboBox<String> cbxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaFactura;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNroFactura;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private int obtenerNuevoIdFactura() {
        int nuevoId = 1; // Valor por defecto en caso de que no se encuentre ningún registro
        try (Connection conexion = ConexionBD.obtenerConexion()) {
            String sql = "SELECT MAX(idFactura) AS maxId FROM facturas";
            try (PreparedStatement ps = conexion.prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    nuevoId = rs.getInt("maxId") + 1;
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al obtener el nuevo ID de factura: " + e.getMessage());
        }
        return nuevoId;
    }
}
