package factura.vista;

// Importación de clases necesarias para la conexión a la base de datos y manejo de excepciones
import factura.dao.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Clase Reporte.
 * Esta clase permite consultar y exportar información de facturas desde la base de datos.
 * 
 * Funcionalidades principales:
 * - Consultar facturas por rango de fechas.
 * - Mostrar los resultados en una tabla interactiva.
 * - Exportar la información de una factura seleccionada a un archivo TXT.
 *
 * @author USUARIO
 */
public class Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents(); // Inicializa los componentes de la interfaz gráfica
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        cargarClientes(); // Carga los clientes en el combo box al iniciar
        configurarTablaClickListener(); // Configura el evento de clic en la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaReporte = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        txtFactura = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        cbxClienteReporte = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CRITERIOS DE CONSULTA");

        jLabel2.setText("Factura :");

        jLabel3.setText("Fecha inicio :");

        jLabel4.setText("Fecha fin :");

        jLabel5.setText("Cliente :");

        tablaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Factura", "Fecha", "Cliente", "Total"
            }
        ));
        jScrollPane2.setViewportView(tablaReporte);

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnExportar.setText("EXPORTAR");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        cbxClienteReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxClienteReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClienteReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxClienteReporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtFactura)
                                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFechaFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                                        .addGap(48, 48, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConsultar))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExportar))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxClienteReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClienteReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClienteReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxClienteReporteActionPerformed

    /**
     * Método realizarConsulta.
     * Consulta las facturas en la base de datos según el rango de fechas proporcionado.
     * Los resultados se muestran en la tabla interactiva.
     */
    private void realizarConsulta() {
        System.out.println("Ejecutando consulta con parámetros:");
        System.out.println("Fecha inicio: " + txtFechaInicio.getText());
        System.out.println("Fecha fin: " + txtFechaFin.getText());

        // Consulta SQL para obtener las facturas dentro del rango de fechas
        String sql = "SELECT numeroFactura, fecha, idCliente, observaciones, total FROM facturas WHERE fecha BETWEEN ? AND ?";
        System.out.println("Consulta SQL: " + sql);
        try (Connection conexion = ConexionBD.obtenerConexion(); PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setString(1, txtFechaInicio.getText()); // Establece la fecha de inicio como parámetro
            ps.setString(2, txtFechaFin.getText()); // Establece la fecha de fin como parámetro

            ResultSet rs = ps.executeQuery(); // Ejecuta la consulta y obtiene los resultados
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaReporte.getModel();
            model.setRowCount(0); // Limpia la tabla antes de mostrar nuevos resultados

            while (rs.next()) {
                // Agrega cada fila de resultados a la tabla
                model.addRow(new Object[]{
                    rs.getString("numeroFactura"),
                    rs.getString("fecha"),
                    rs.getInt("idCliente"),
                    rs.getString("observaciones"),
                    rs.getDouble("total")
                });
            }
        } catch (SQLException e) {
            e.printStackTrace(); // Imprime la traza de la excepción en caso de error
        }
    }

    /**
     * Método configurarTablaClickListener.
     * Configura un evento de clic en la tabla para actualizar los campos de texto y el combo box
     * con la información de la factura seleccionada.
     */
    private void configurarTablaClickListener() {
        tablaReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = tablaReporte.getSelectedRow(); // Obtiene la fila seleccionada
                if (selectedRow != -1) {
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaReporte.getModel();
                    txtFactura.setText(model.getValueAt(selectedRow, 0).toString()); // Actualiza el campo de texto con el número de factura

                    // Consulta para obtener el nombre del cliente según el ID
                    String idCliente = model.getValueAt(selectedRow, 2).toString();
                    String sqlCliente = "SELECT nombre FROM clientes WHERE idCliente = ?";
                    try (Connection conexion = ConexionBD.obtenerConexion(); PreparedStatement ps = conexion.prepareStatement(sqlCliente)) {
                        ps.setString(1, idCliente); // Establece el ID del cliente como parámetro
                        ResultSet rs = ps.executeQuery(); // Ejecuta la consulta
                        if (rs.next()) {
                            cbxClienteReporte.setSelectedItem(rs.getString("nombre")); // Actualiza el combo box con el nombre del cliente
                        }
                    } catch (SQLException e) {
                        e.printStackTrace(); // Imprime la traza de la excepción en caso de error
                    }
                }
            }
        });
    }

    /**
     * Método cargarClientes.
     * Carga los nombres de los clientes desde la base de datos y los agrega al combo box.
     */
    private void cargarClientes() {
        String sql = "SELECT idCliente, nombre FROM clientes"; // Consulta SQL para obtener los clientes
        try (Connection conexion = ConexionBD.obtenerConexion(); PreparedStatement ps = conexion.prepareStatement(sql)) {
            ResultSet rs = ps.executeQuery(); // Ejecuta la consulta y obtiene los resultados
            cbxClienteReporte.removeAllItems(); // Limpia el combo box antes de agregar nuevos elementos
            while (rs.next()) {
                cbxClienteReporte.addItem(rs.getString("nombre")); // Agrega cada cliente al combo box
            }
        } catch (SQLException e) {
            e.printStackTrace(); // Imprime la traza de la excepción en caso de error
        }
    }

    /**
     * Método que se ejecuta al presionar el botón "Consultar"
     */
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        realizarConsulta(); // Llama al método para realizar la consulta
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * Método que se ejecuta al presionar el botón "Exportar"
     */
    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
                String numeroFactura = txtFactura.getText(); // Obtiene el número de factura del campo de texto
                if (numeroFactura.isEmpty()) {
                    System.out.println("No se ha seleccionado ninguna factura para exportar."); // Mensaje en consola si no hay factura seleccionada
                    javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una factura antes de exportar."); // Mensaje en la interfaz
                    return;
                }

                String sql = "SELECT numeroFactura, fecha, idCliente, observaciones, total FROM facturas WHERE numeroFactura = ?"; // Consulta SQL para obtener los datos de la factura
                try (Connection conexion = ConexionBD.obtenerConexion(); PreparedStatement ps = conexion.prepareStatement(sql)) {
                    ps.setString(1, numeroFactura); // Establece el número de factura como parámetro
                    ResultSet rs = ps.executeQuery(); // Ejecuta la consulta

                    if (rs.next()) {
                        // Crea el contenido del archivo TXT con los datos de la factura
                        String contenido = "Factura: " + rs.getString("numeroFactura") + "\n" +
                                          "Fecha: " + rs.getString("fecha") + "\n" +
                                          "Cliente: " + rs.getInt("idCliente") + "\n" +
                                          "Observaciones: " + rs.getString("observaciones") + "\n" +
                                          "Total: " + rs.getDouble("total") + "\n";

                        java.nio.file.Path path = java.nio.file.Paths.get("factura_" + numeroFactura + ".txt"); // Define la ruta del archivo
                        java.nio.file.Files.write(path, contenido.getBytes()); // Escribe el contenido en el archivo
                        System.out.println("Factura exportada exitosamente: " + path.toAbsolutePath()); // Mensaje en consola indicando éxito
                        javax.swing.JOptionPane.showMessageDialog(this, "Factura exportada exitosamente."); // Mensaje en la interfaz

                        java.awt.Desktop.getDesktop().open(path.toFile()); // Abre el archivo automáticamente
                    } else {
                        System.out.println("No se encontraron datos para la factura: " + numeroFactura); // Mensaje en consola si no se encuentran datos
                        javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron datos para la factura seleccionada."); // Mensaje en la interfaz
                    }
                } catch (SQLException | java.io.IOException e) {
                    e.printStackTrace(); // Imprime la traza de la excepción en caso de error
                    System.out.println("Error al exportar la factura: " + e.getMessage()); // Mensaje en consola indicando error
                    javax.swing.JOptionPane.showMessageDialog(this, "Error al exportar la factura."); // Mensaje en la interfaz
                }
    }//GEN-LAST:event_btnExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JComboBox<String> cbxClienteReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaReporte;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    // End of variables declaration//GEN-END:variables
}
